name: CI

on:
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    needs: [build-arm64]
    steps:
      - id: get-latest-release
        name: Get latest qbee-agent release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: qbee-io/qbee-agent
          excludes: prelease,draft
     
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cloud-image-utils qemu-utils qemu-system-x86 gettext-base

      - name: Change permissions of /dev/kvm
        run: |
          if [ ! -c /dev/kvm ]; then
            echo "/dev/kvm does not exist, skipping permission change"
            exit 0
          fi
          sudo chmod 666 /dev/kvm

      - name: Run build script
        run: |
          echo "Latest qbee-agent release: ${{ steps.get-latest-release.outputs.release }}"
          export QBEE_AGENT_VERSION="${{ steps.get-latest-release.outputs.release }}"
          bash debian/docker-build.sh amd64

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./debian/files
          file: ./debian/Dockerfile.amd64
          push: true
          tags: |
            qbeeio/qbee-demo:latest-amd64
            qbeeio/qbee-demo:latest-debian-amd64
            qbeeio/qbee-demo:${{ steps.get-latest-release.outputs.release }}-debian-amd64
          platforms: linux/amd64

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create qbeeio/qbee-demo:latest \
            qbeeio/qbee-demo:latest-amd64 \
            qbeeio/qbee-demo:latest-arm64

          docker manifest create qbeeio/qbee-demo:latest-debian \
            qbeeio/qbee-demo:latest-debian-amd64 \
            qbeeio/qbee-demo:latest-debian-arm64

          LATEST_RELEASE=${{ steps.get-latest-release.outputs.release }}

          docker manifest create qbeeio/qbee-demo:${LATEST_RELEASE}-debian \
            qbeeio/qbee-demo:${LATEST_RELEASE}-debian-amd64 \
            qbeeio/qbee-demo:${LATEST_RELEASE}-debian-arm64

          docker manifest push qbeeio/qbee-demo:latest
          docker manifest push qbeeio/qbee-demo:latest-debian
          docker manifest push qbeeio/qbee-demo:${LATEST_RELEASE}-debian

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - id: get-latest-release
        name: Get latest qbee-agent release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: qbee-io/qbee-agent
          excludes: prelease,draft

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cloud-image-utils qemu-utils qemu-system-arm gettext-base

      - name: Change permissions of /dev/kvm
        run: |
          if [ ! -c /dev/kvm ]; then
            echo "/dev/kvm does not exist, skipping permission change"
            exit 0
          fi
          sudo chmod 666 /dev/kvm

      - name: Run build script
        run: |
          echo "Latest qbee-agent release: ${{ steps.get-latest-release.outputs.release }}"
          export QBEE_AGENT_VERSION="${{ steps.get-latest-release.outputs.release }}"
          bash debian/docker-build.sh arm64

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./debian/files
          file: ./debian/Dockerfile.arm64
          push: true
          tags: |
            qbeeio/qbee-demo:latest-arm64
            qbeeio/qbee-demo:latest-debian-arm64
            qbeeio/qbee-demo:${{ steps.get-latest-release.outputs.release }}-debian-arm64
          platforms: linux/arm64

