name: CI

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    needs: [build-arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: build
        name: Build and push image
        uses: ./.github/actions/build-debian
        with:
          arch: amd64
          qemu-package: qemu-system-x86
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create qbeeio/qbee-demo:latest \
            qbeeio/qbee-demo:latest-amd64 \
            qbeeio/qbee-demo:latest-arm64

          docker manifest create qbeeio/qbee-demo:latest-debian \
            qbeeio/qbee-demo:latest-debian-amd64 \
            qbeeio/qbee-demo:latest-debian-arm64

          LATEST_RELEASE=${{ steps.build.outputs.release }}

          docker manifest create qbeeio/qbee-demo:${LATEST_RELEASE}-debian \
            qbeeio/qbee-demo:${LATEST_RELEASE}-debian-amd64 \
            qbeeio/qbee-demo:${LATEST_RELEASE}-debian-arm64

          docker manifest push qbeeio/qbee-demo:latest
          docker manifest push qbeeio/qbee-demo:latest-debian
          docker manifest push qbeeio/qbee-demo:${LATEST_RELEASE}-debian

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push image
        uses: ./.github/actions/build-debian
        with:
          arch: arm64
          qemu-package: qemu-system-arm
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

