name: Test Self-Hosted Runner
on: [push]
permissions: 
    contents: read

jobs:
  test:
    runs-on: 
        labels: [self-hosted, Linux, X64]
        group: "public-group"
    steps:
      - name: Ping
        run: echo "Runner is working!"